### ISSUE TITLE
Do not trigger DNS in *SearchPipeTest

### ISSUE THREAD

**Issue by Akron** [KorAP/Kustvakt#391]
**Kustvakt version**
0.67

**Describe the bug**
When running the test suite in an environment with problematic DNS resolution, the test suite fails.

**To Reproduce**
Use a problematic test environment. That's not too easy to reproduce, but for example the IDS-Gast environment fails to resolve problematic domain names like `glemm` and `unknown`.

**Expected behavior**
The DNS should not be triggered and the test suite should run through.

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by Akron** [comment]
The error persists:
```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.407 s <<< FAILURE! -- in de.ids_mannheim.korap.web.controller.SearchNetworkEndpointTest
[ERROR] de.ids_mannheim.korap.web.controller.SearchNetworkEndpointTest.testSearchWithUnknownHost -- Time elapsed: 0.607 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <118> but was: <201>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:158)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:139)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:201)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:558)
	at de.ids_mannheim.korap.web.controller.SearchNetworkEndpointTest.testSearchWithUnknownHost(SearchNetworkEndpointTest.java:109)

[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.460 s <<< FAILURE! -- in de.ids_mannheim.korap.web.lite.SearchNetworkEndpointTest
[ERROR] de.ids_mannheim.korap.web.lite.SearchNetworkEndpointTest.testSearchWithUnknownHost -- Time elapsed: 0.158 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <118> but was: <201>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:158)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:139)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:201)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:147)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:558)
	at de.ids_mannheim.korap.web.lite.SearchNetworkEndpointTest.testSearchWithUnknownHost(SearchNetworkEndpointTest.java:108)
```
